version: '3.8'

services:
  # Trading App Backend
  trading-app:
    build: .
    container_name: trading-app-backend
    # Note: Port 3000 is only exposed to localhost (host machine)
    # Nginx on the host will proxy external traffic to this port
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=trading_user
      - DB_PASSWORD=trading_password
      - DB_DATABASE=trading_app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KITE_API_KEY=${KITE_API_KEY}
      - KITE_API_SECRET=${KITE_API_SECRET}
      - KITE_ACCESS_TOKEN=${KITE_ACCESS_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DATA_PROVIDER=${DATA_PROVIDER}
      - VORTEX_APP_ID=${VORTEX_APP_ID}
      - VORTEX_API_KEY=${VORTEX_API_KEY}
      - VORTEX_CREATE_SESSION_URL=${VORTEX_CREATE_SESSION_URL}
      - VORTEX_BASE_URL=${VORTEX_BASE_URL}
      - VORTEX_WS_URL=${VORTEX_WS_URL}
      - VORTEX_REDIRECT_URI=${VORTEX_REDIRECT_URI}
      - VORTEX_INSTRUMENTS_CSV_URL=${VORTEX_INSTRUMENTS_CSV_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "dist/health-check.js"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Postgres Database
  postgres:
    image: postgres:15-alpine
    container_name: trading-postgres
    environment:
      - POSTGRES_DB=trading_app
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=trading_password
    # Expose only to internal network, not host (security)
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks:
      - trading-network
    # Resource limits for production stability
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: trading-redis
    # Expose only to internal network, not host (security)
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - trading-network
    # Resource limits for production stability
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  postgres_data:
  redis_data:

networks:
  trading-network:
    driver: bridge
